### ISSUE TITLE
Fix instance where InvalidTaskException during add is not thrown

### ISSUE THREAD

**Issue by NatashaKSS** [cs2103aug2015-w13-2j/main#126]
- Error reconstruction, when the command:
  add [WHITESPACE entered here]
  Task class throws a NullPointerException

**Comment by chunqi** [comment]
I was able to reproduce this bug. The cause is Parser trimming the whitespace after checking hasNext(). If the rest of the command is purely whitespace, the trim() method will advance the mParserPos until the end of the command string. The next peek() call in the GENERAL state will cause IndexOutOfBoundsException. I will be fixing this in the next commit.
